// Lucide icons — clean, consistent SVG.
// We only import the names we actually use, so tree-shaking keeps the bundle small.

import {
  Heart,
  Sparkles,
  Star,
  Crown,
  Lock,
  CheckCircle2,
  Map as MapIcon,
  Home,
  BookOpen,
  Mail,
  MailOpen,
  Settings,
  Compass,
  Target,
  Trophy,
  Flame,
  GraduationCap,
  Stethoscope,
  Pill,
  Syringe,
  Building2,
  Briefcase,
  FileText,
  ScrollText,
  Sword,
  Dumbbell,
  ClipboardList,
  NotebookPen,
  Send,
  ArrowUpRight,
  ArrowRight,
  ChevronRight,
  X,
  Menu,
  Bell,
  Plus,
  Trash2,
  RotateCcw,
  ExternalLink,
  Sprout,
  Flower,
  Flower2,
  Cherry,
  Cake,
  Cookie,
  Gift,
  Cloud,
  Bookmark,
  Library,
  PenLine,
  Smile,
  Volume2,
  VolumeX,
  Eye,
  EyeOff,
  Zap,
  PartyPopper,
  Wand2,
  Coffee,
  GlassWater,
  Lightbulb,
  HeartHandshake,
  HandHeart,
  Calendar,
  CalendarHeart,
  Award,
} from 'lucide-static';

const map: Record<string, string> = {
  heart: Heart,
  sparkles: Sparkles,
  star: Star,
  crown: Crown,
  lock: Lock,
  check: CheckCircle2,
  map: MapIcon,
  home: Home,
  book: BookOpen,
  mail: Mail,
  'mail-open': MailOpen,
  settings: Settings,
  compass: Compass,
  target: Target,
  trophy: Trophy,
  flame: Flame,
  cap: GraduationCap,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  building: Building2,
  briefcase: Briefcase,
  file: FileText,
  scroll: ScrollText,
  sword: Sword,
  dumbbell: Dumbbell,
  clipboard: ClipboardList,
  pen: NotebookPen,
  send: Send,
  'arrow-up-right': ArrowUpRight,
  'arrow-right': ArrowRight,
  chevron: ChevronRight,
  x: X,
  menu: Menu,
  bell: Bell,
  plus: Plus,
  trash: Trash2,
  reset: RotateCcw,
  external: ExternalLink,
  sprout: Sprout,
  flower: Flower,
  flower2: Flower2,
  cherry: Cherry,
  cake: Cake,
  cookie: Cookie,
  gift: Gift,
  cloud: Cloud,
  bookmark: Bookmark,
  library: Library,
  penline: PenLine,
  smile: Smile,
  volume: Volume2,
  volumex: VolumeX,
  eye: Eye,
  eyeoff: EyeOff,
  zap: Zap,
  party: PartyPopper,
  wand: Wand2,
  coffee: Coffee,
  glass: GlassWater,
  lightbulb: Lightbulb,
  hearts: HeartHandshake,
  handheart: HandHeart,
  calendar: Calendar,
  calendarheart: CalendarHeart,
  award: Award,
};

export type IconName = keyof typeof map;

/**
 * Returns a Lucide icon as inline SVG with proper sizing.
 * stroke="currentColor" so it inherits from CSS.
 */
export function icon(name: IconName | string, size = 24, className = ''): string {
  const raw = map[name];
  if (!raw) return '';
  // Lucide-static svgs come with stroke="currentColor" already.
  // Inject width/height/class.
  return raw
    .replace('<svg', `<svg width="${size}" height="${size}" class="${className}" aria-hidden="true"`);
}

/**
 * Inline icon, no wrapper.
 */
export function iconRaw(name: IconName | string): string {
  return map[name] ?? '';
}
